name: Rust Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: moonrepo/setup-rust@v1
      with:
        rust-version: '1.73.0'

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Create release folder
      run: |
        mkdir -p release
        cp target/release/accelerator-rs release/

    - name: Commit release files
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'
        message: 'Add release files'
        add: 'release/**'
